### ISSUE TITLE
Question: What is the expire parameter in queue.send used for?

### ISSUE THREAD

**Issue by sradhakrishna** [kushaldas/retask#14]
Hi,

What exactly is the expire parameter in queue.send used for?

Suppose a producer has enqueued a task. A consumer has processed the task and invokes queue.send to signal that it has completed the task and to return some information about processing the task.

Is it that the return value will not reach the producer once the expire time is lapsed?

Radha.

**Comment by kushaldas** [comment]
> Is it that the return value will not reach the producer once the expire time is lapsed?

Yes, redis will delete that value from the queue.
